[build]
builder = "heroku/buildpacks:20"

[deploy]
start = "gunicorn spacejunk.wsgi:application --bind 0.0.0.0:$PORT"

[env]
PYTHONUNBUFFERED = "1"
PORT = "8080"
DJANGO_SETTINGS_MODULE = "spacejunk.settings"
